# Header
menu:
  主页: /
  归档: /archives
  知乎: https://www.zhihu.com/people/liu-mou-ren-34-33
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: false
mathjax: false

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts
- links

# Links
links:
  个人主页: https://afdian.net/a/lj92458?tab=feed
  抖音福利: https://www.douyin.com/user/MS4wLjABAAAAVH9WuKlaNpy_bX0piLR9sK1GWkCfXdTv-NUcyG2dyyk
  知乎: https://www.zhihu.com/people/liu-mou-ren-34-33
  twitter: https://twitter.com/liulangzhe_lj

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins: 
fb_app_id:

# 评论系统
duoshuo_shortname: your_shortname
disqus_shortname: your_shortname

# Baidu share
baidushare: true